name: "✨ Feature"
description: "새로운 기능 추가"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## 기능 요청
        새로운 기능을 추가하기 위한 요청입니다. 아래 항목들을 작성해주세요.

  - type: textarea
    attributes:
      label: 📄 기능 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      value: |
        ## 기능 개요
        - 기능의 목적
        - 주요 기능
        - 사용자에게 주는 이점
        
        ## 기술적 고려사항
        - 사용할 기술 스택
        - 성능 고려사항
        - 보안 고려사항
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업 내용
      description: 구현해야 할 작업들을 체크리스트 형태로 작성해주세요.
      value: |
        ## 백엔드
        - [ ] 엔티티 설계
        - [ ] DTO 클래스 생성
        - [ ] Repository 구현
        - [ ] Service 로직 구현
        - [ ] Controller 구현
        - [ ] 테스트 코드 작성
        
        ## 프론트엔드
        - [ ] 컴포넌트 설계
        - [ ] API 연동
        - [ ] UI/UX 구현
        - [ ] 테스트 코드 작성
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📋 참고 자료
      description: 참고할 자료가 있다면 링크를 첨부해주세요.
      value: |
        ## 문서
        - API 문서: 
        - 디자인 시안: 
        - 관련 이슈: 
        
        ## 기타
        - 참고할 코드: 
        - 참고할 라이브러리: 