name: Discord Notification

on:
  issues:
    types: [ opened, closed ]
  pull_request:
    types: [ opened, closed, merged ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ${{ github.event_name == 'issues' && github.event.action == 'closed' && '🎉 **이슈가 닫혔습니다!**\n🔹 Repository: ${{ github.repository }}\n🔹 이슈 제목: ${{ github.event.issue.title }}\n🔗 [GitHub에서 보기](${{ github.event.issue.html_url }})' || 
            github.event_name == 'pull_request' && github.event.action == 'closed' && '🎉 **PR이 닫혔습니다!**\n🔹 Repository: ${{ github.repository }}\n🔹 PR 제목: ${{ github.event.pull_request.title }}\n🔗 [GitHub에서 보기](${{ github.event.pull_request.html_url }})' ||
            '🚀 **새로운 GitHub 이벤트!**\n🔹 Repository: ${{ github.repository }}\n🔹 이벤트: ${{ github.event_name }}\n🔗 [GitHub에서 보기](${{ github.event.issue.html_url || github.event.pull_request.html_url }})'
